"use strict";

const fs = require("fs-extra");
const path = require("path");
const uglifyes = require("uglify-es");
const cleancss = require("clean-css");
const htmlminifier = require("html-minifier");

const TEMPLATE = path.join(__dirname, "page.hbs");
const STATIC = path.join(__dirname, "static");
const STATIC_BUILD = path.join(__dirname, "build_static");

const concat_static_files_of_type = async (ext) =>
  fs.readdir(STATIC)
    .then(files => files.filter(f => new RegExp(`\\.${ext}$`, "i").test(f)))
    .then(files => Promise.all(files.map(f => fs.readFile(path.join(STATIC, f), "utf8"))))
    .then(files => files.reduce((js, f) => js + f, ""));

const minify_html = html => htmlminifier.minify(html, {
  collapseBooleanAttributes: true,
  collapseInlineTagWhitespace: true,
  collapseWhitespace: true,
  decodeEntities: true,
  ignoreCustomFragments: [/{{{?[^{}]+}}}?/],
  includeAutoGeneratedTags: true,
  keepClosingSlash: false,
  minifyCSS: false,
  minifyJS: false,
  minifyURLs: false,
  preserveLineBreaks: false,
  preventAttributesEscaping: false,
  processConditionalComments: false,
  removeAttributeQuotes: true,
  removeComments: true,
  removeEmptyAttributes: false,
  removeEmptyElements: false,
  removeOptionalTags: true,
  removeRedundantAttributes: true,
  removeScriptTypeAttributes: true,
  removeStyleLinkTypeAttributes: true,
  removeTagWhitespace: true,
  sortAttributes: true,
  sortClassName: true,
  useShortDoctype: true,
});

const minify_js = js => uglifyes.minify(js, {
  mangle: true,
  compress: {
    booleans: true,
    collapse_vars: true,
    comparisons: true,
    conditionals: true,
    dead_code: true,
    drop_console: true,
    drop_debugger: true,
    evaluate: true,
    hoist_funs: true,
    hoist_vars: false,
    if_return: true,
    join_vars: true,
    keep_fargs: false,
    keep_fnames: false,
    loops: true,
    negate_iife: true,
    properties: true,
    reduce_vars: true,
    sequences: true,
    unsafe: true,
    unused: true,
  },
}).code;

const minify_css = css => new cleancss({
  returnPromise: true,
}).minify(css)
  .then(({styles}) => styles);

fs.ensureDir(STATIC_BUILD)
  .then(() => Promise.all([
    concat_static_files_of_type("js")
      .then(minify_js)
      .then(js => fs.writeFile(path.join(STATIC_BUILD, "script.js"), js)),
    concat_static_files_of_type("css")
      .then(minify_css)
      .then(css => fs.writeFile(path.join(STATIC_BUILD, "style.css"), css)),
    fs.readFile(TEMPLATE, "utf8")
      .then(minify_html)
      .then(html => fs.writeFile(path.join(__dirname, "build.hbs"), html)),
  ]));
